### ISSUE TITLE
but why?

### ISSUE THREAD

**Issue by patilkrunal** [meehawk/tuber#1]

**Comment by meehawk** [comment]
@patilkrunal sorry with the delay in response. I had undergone a minor surgery past week. This is a little fun project I did from a question asked in one of the coding interviews in Javascript to transform a string to a weird pattern.

**Comment by patilkrunal** [comment]
Was curious why you put this on auto-commit every hour. Is it to make your contributions graphs greener?
Take care of your health mate.
